### ISSUE TITLE
any help 

### ISSUE THREAD

**Issue by prince911** [M0tHs3C/Argo#4]
i cant use the tool wahit i miss 

![Uploading Screenshot_2020-04-25_21-57-57.png…]()

**Comment by prince911** [comment]
way you close ??

**Comment by M0tHs3C** [comment]
no title for the supposed error
don't open a ticket If you don't know what you are doing, I suggest you to
NOT use this tool because i don't think you are able to use it correctly or
for not so good reason.
if the tool isn't working because it's your fault u can just open a ticket.
the please cure you form, your english it's unreadable
I'm not here to babysit everyone

Il dom 26 apr 2020, 16:32 prince911 <notifications@github.com> ha scritto:

**Comment by prince911** [comment]
I apologize, I wanted to try the tool
I wish a happy time, peace
